"""initial

Revision ID: bfdf8aed1c48
Revises: 
Create Date: 2026-05-28 20:18:37.907752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdf8aed1c48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('notif_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enlace', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('notif_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
