"""initial

Revision ID: 9c0f4450dd12
Revises: 
Create Date: 2026-05-28 20:01:27.927469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0f4450dd12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('descripcion_sintomas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('cita_id')
    )
    op.create_index('ix_citas_estado', 'citas', ['estado'], unique=False)
    op.create_index('ix_citas_fecha_cita', 'citas', ['fecha_cita'], unique=False)
    op.create_index('ix_citas_medico_id', 'citas', ['medico_id'], unique=False)
    op.create_index('ix_citas_usuario_id', 'citas', ['usuario_id'], unique=False)
    op.create_table('historial_estado',
    sa.Column('historial_id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('realizado_por', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.cita_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_table('recordatorios',
    sa.Column('recordatorio_id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('programado_para', sa.TIMESTAMP(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.cita_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recordatorio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordatorios')
    op.drop_table('historial_estado')
    op.drop_index('ix_citas_usuario_id', table_name='citas')
    op.drop_index('ix_citas_medico_id', table_name='citas')
    op.drop_index('ix_citas_fecha_cita', table_name='citas')
    op.drop_index('ix_citas_estado', table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
