"""initial_migration

Revision ID: 46ea1703be6b
Revises: 
Create Date: 2026-04-01 19:27:35.853618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ea1703be6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales',
    sa.Column('credencial_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), server_default=sa.text("'usuario'"), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('intentos_fallidos', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bloqueado_hasta', sa.TIMESTAMP(), nullable=True),
    sa.Column('tiene_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('credencial_id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index('ix_credenciales_correo', 'credenciales', ['correo'], unique=False)
    op.create_index('ix_credenciales_usuario_id', 'credenciales', ['usuario_id'], unique=False)
    op.create_table('log_autenticacion',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('credencial_id', sa.UUID(), nullable=False),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('agente_usuario', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credenciales.credencial_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_log_autenticacion_creado_en', 'log_autenticacion', ['creado_en'], unique=False)
    op.create_index('ix_log_autenticacion_credencial_id', 'log_autenticacion', ['credencial_id'], unique=False)
    op.create_index('ix_log_autenticacion_credencial_id_creado_en', 'log_autenticacion', ['credencial_id', 'creado_en'], unique=False)
    op.create_table('registro_2fa',
    sa.Column('registro_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('credencial_id', sa.UUID(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('usado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credenciales.credencial_id'], ),
    sa.PrimaryKeyConstraint('registro_id')
    )
    op.create_index('ix_registro_2fa_credencial_id', 'registro_2fa', ['credencial_id'], unique=False)
    op.create_index('ix_registro_2fa_usado_expira_en', 'registro_2fa', ['usado', 'expira_en'], unique=False)
    op.create_table('token_recuperacion',
    sa.Column('token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('credencial_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('usado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credenciales.credencial_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_token_recuperacion_credencial_id', 'token_recuperacion', ['credencial_id'], unique=False)
    op.create_index('ix_token_recuperacion_token_hash', 'token_recuperacion', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_recuperacion_token_hash', table_name='token_recuperacion')
    op.drop_index('ix_token_recuperacion_credencial_id', table_name='token_recuperacion')
    op.drop_table('token_recuperacion')
    op.drop_index('ix_registro_2fa_usado_expira_en', table_name='registro_2fa')
    op.drop_index('ix_registro_2fa_credencial_id', table_name='registro_2fa')
    op.drop_table('registro_2fa')
    op.drop_index('ix_log_autenticacion_credencial_id_creado_en', table_name='log_autenticacion')
    op.drop_index('ix_log_autenticacion_credencial_id', table_name='log_autenticacion')
    op.drop_index('ix_log_autenticacion_creado_en', table_name='log_autenticacion')
    op.drop_table('log_autenticacion')
    op.drop_index('ix_credenciales_usuario_id', table_name='credenciales')
    op.drop_index('ix_credenciales_correo', table_name='credenciales')
    op.drop_table('credenciales')
    # ### end Alembic commands ###
