"""initial

Revision ID: dabf49b70012
Revises: 
Create Date: 2026-05-28 19:58:16.473363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabf49b70012'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('afiliaciones',
    sa.Column('afiliacion_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_afiliacion', sa.String(length=20), nullable=False),
    sa.Column('numero_poliza', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'activo'"), nullable=False),
    sa.Column('fecha_afiliacion', sa.Date(), nullable=False),
    sa.Column('medico_asignado_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('afiliacion_id'),
    sa.UniqueConstraint('numero_poliza'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('informacion_medica',
    sa.Column('info_medica_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_sangre', sa.String(length=5), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('enfermedades_cronicas', sa.Text(), nullable=True),
    sa.Column('medicamentos_actuales', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('info_medica_id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informacion_medica')
    op.drop_table('afiliaciones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
