"""initial

Revision ID: 4ff952acbd99
Revises: 
Create Date: 2026-05-28 20:03:50.826967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff952acbd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('medico_id', sa.Uuid(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_registro', sa.String(length=50), nullable=False),
    sa.Column('correo_institucional', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('medico_id'),
    sa.UniqueConstraint('correo_institucional'),
    sa.UniqueConstraint('numero_registro')
    )
    op.create_index('medico_registro', 'medicos', ['numero_registro'], unique=False)
    op.create_table('sedes',
    sa.Column('sede_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sede_id')
    )
    op.create_table('servicios',
    sa.Column('servicio_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('servicio_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('nombre_servicio', 'servicios', ['nombre'], unique=False)
    op.create_table('especialidades',
    sa.Column('especialidad_id', sa.Uuid(), nullable=False),
    sa.Column('servicio_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_cita_minutos', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.servicio_id'], ),
    sa.PrimaryKeyConstraint('especialidad_id')
    )
    op.create_index('especialidad_nombre', 'especialidades', ['nombre'], unique=False)
    op.create_table('disponibilidades',
    sa.Column('disponibilidad_id', sa.Uuid(), nullable=False),
    sa.Column('medico_id', sa.Uuid(), nullable=False),
    sa.Column('especialidad_id', sa.Uuid(), nullable=False),
    sa.Column('sede_id', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 1 AND 7', name='ck_disponibilidad_dia_semana'),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.especialidad_id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.medico_id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.sede_id'], ),
    sa.PrimaryKeyConstraint('disponibilidad_id')
    )
    op.create_index('disponibilidad_medico_fecha', 'disponibilidades', ['medico_id', 'dia_semana', 'hora_inicio'], unique=False)
    op.create_table('medico_especialidades',
    sa.Column('medico_especialidad_id', sa.Uuid(), nullable=False),
    sa.Column('medico_id', sa.Uuid(), nullable=False),
    sa.Column('especialidad_id', sa.Uuid(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.especialidad_id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.medico_id'], ),
    sa.PrimaryKeyConstraint('medico_especialidad_id'),
    sa.UniqueConstraint('medico_id', 'especialidad_id', name='uq_medico_especialidad_medico_especialidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medico_especialidades')
    op.drop_index('disponibilidad_medico_fecha', table_name='disponibilidades')
    op.drop_table('disponibilidades')
    op.drop_index('especialidad_nombre', table_name='especialidades')
    op.drop_table('especialidades')
    op.drop_index('nombre_servicio', table_name='servicios')
    op.drop_table('servicios')
    op.drop_table('sedes')
    op.drop_index('medico_registro', table_name='medicos')
    op.drop_table('medicos')
    # ### end Alembic commands ###
