"""crear tablas iniciales

Revision ID: 33545c25dea5
Revises: 
Create Date: 2026-04-02 18:28:57.633795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33545c25dea5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversacion',
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('conversacion_id')
    )
    op.create_table('clasificacion_sintomas',
    sa.Column('clasificacion_id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('terminos_identificados', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('especialidad_sugerida', sa.String(length=100), nullable=True),
    sa.Column('nivel_urgencia', sa.String(length=20), nullable=False),
    sa.Column('confianza_modelo', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion.conversacion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clasificacion_id'),
    sa.UniqueConstraint('conversacion_id')
    )
    op.create_table('mensaje',
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('remitente', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion.conversacion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    op.drop_table('clasificacion_sintomas')
    op.drop_table('conversacion')
    # ### end Alembic commands ###
